FROM golang:1.9.4-alpine
WORKDIR /app
COPY go-workspace /app/go-workspace
# ARG GOPATH=/app/go-workspace
# ARG GOBIN=/app
RUN export GOPATH=/app/go-workspace && export GOBIN=/app && go install /app/go-workspace/src/github.com/counting-frontend/cmd/counting-frontend/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates

COPY --from=0 /app/main /main

CMD ["/main"]
