kind: Service
apiVersion: v1
metadata:
  name: shot-counter-frontend
spec:
  type: LoadBalancer
  loadBalancerIP: 35.227.124.115
  selector:
    app: shot-counter-frontend
  ports:
  - protocol: TCP
    port: 8080
